version: '3'
services:
    app:
        build:
            args:
                user: crater-user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: crater-php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - './:/var/www'
            - './docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated'
        networks:
            - crater
    db:
        image: mariadb
        restart: always
        volumes:
            - 'db:/var/lib/mysql'
        environment:
            MYSQL_USER: crater
            MYSQL_PASSWORD: crater
            MYSQL_DATABASE: crater
            MYSQL_ROOT_PASSWORD: crater
        ports:
            - '33006:3306'
        networks:
            - crater
    nginx:
        image: 'nginx:1.17-alpine'
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - './:/var/www'
            - './docker-compose/nginx:/etc/nginx/conf.d/'
        networks:
            - crater
    cron:
        build:
            context: ./
            dockerfile: ./docker-compose/cron.dockerfile
        volumes:
            - './:/var/www'
        networks:
            - crater
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
volumes:
    db: null
    sail-mysql:
        driver: local
networks:
    crater:
        driver: bridge
